### ISSUE TITLE
Merge files ar/ascii/regular and postal code with the city files

### ISSUE THREAD

**Issue by seddik** [bensialih/algeria-cities#114]
It is better to merge the files so when we do changes we do it in one file only, also for the postal codes they have a separate file, we can just inject it in the main file so we get only one file for each type CSV/JSON/ ... we can use a suffix for example name_ar: , name_ascii:, name: instead of creating 3 files for each format.

if it is okey let me know so I create a new pull request

**Comment by bensialih** [comment]
Do you think we should have one source of truth?
maybe it can be sql or json and a converter script that will change between the different formats?

**Comment by seddik** [comment]
at first I was confused, I didn't seen the algerian-cities.json file, I thougt they were separated, it is  safe to close this issue !
