### ISSUE TITLE
Separate code from data (Python folder)

### ISSUE THREAD

**Issue by seddik** [bensialih/algeria-cities#179]
I think we shoud put the scripts code in a separate folder, so all scripts would be in a separate folder, we can name it src, code, ...

![image](https://github.com/bensialih/algeria-cities/assets/6674347/4d5b64c2-d646-41c6-8a9f-41d7c959a0ab)

**Comment by bensialih** [comment]
is everything going into source folder?
ie python, php, and dart folders?

**Comment by seddik** [comment]
yes I suppose so, so we don't get confused between data and scripts
